# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: node:6.9.4
image: beevelop/ionic:latest
clone:
  depth: full
pipelines:
  default:
    - step:
        caches:
          - node 
        deployment: production
        script:
          - npm install
          - npm run build
          # - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
          # - ionic login
          - ionic upload --deploy=dev --note="$BITBUCKET_COMMIT"
